Implement checks for empty objects
distribusion/supa pull request #18
Opened 2017-01-23 10:44 UTC by SamyRai

2017-01-23 14:10 UTC, ghost approved these changes

2017-01-23 15:06 UTC, goozzik commented on README.md
Is the documentation going to be added or you would you like to do this as part of other story?

2017-01-23 15:08 UTC, jrietema submitted a review, later dismissed
Not such a fan of the `virtual` naming but I get why you used it. Can you add a `getter: Proc.new...` as a virtual attribute? Wouldn't be very static then :wink:. I need to try this.

Looks like we have a gap in documentation examples, I wouldn't say we can't release without them, but let's complete them soon after?

2017-01-23 15:08 UTC, jrietema commented on README.md
> +[![Build Status](https://travis-ci.org/dasnotme/supa.svg?branch=master)](https://travis-ci.org/dasnotme/supa)
Looks like the badges got leaked... revert to badge definitions of `distribusion/supa` repo

2017-01-23 15:08 UTC, jrietema commented on README.md
> -### 1. Method name
looks like this example is still fitting the implementation if `exec_context` is added

2017-01-23 15:08 UTC, jrietema commented on README.md
> -Attributes will be retrieved from correspondingly named instance methods unless a getter is defined:
this example is still relevant

2017-01-23 15:08 UTC, jrietema commented on README.md
> -Literal values can be supplied as `String`, `Numeric`, `Time`, `Date`, etc.
looks like this example could be used for the `virtual` attribute

2017-01-23 15:08 UTC, jrietema commented on README.md
> -###2. Hash key
I don't think we have similar functionality now in the new version - can be left out.

2017-01-23 15:08 UTC, jrietema commented on README.md
> -## `collection`
can we apply some examples to the `collection` command?

2017-01-23 15:08 UTC, jrietema commented on README.md
> +### `append`
no examples here?

2017-01-23 15:08 UTC, jrietema commented on lib/supa/command.rb
> +      !options[:modifier].nil?
maybe use wrapper (since it's defined and needed in the same context):
```
!modifier.nil?
```

2017-01-23 15:08 UTC, jrietema commented on lib/supa/command.rb
> +      options[:exec_context] != :representer
I don't like this negative definition... it's not like the user specified to execute on object and it seems unintuitive. Should more possible option values be introduced this wouldn't be valid anymore. Maybe refactor to:
```
def exec_on_representer?
  options[:exec_context] == :representer
end
```
Then the `dynamic_value` method will better reflect that there's only one option.

2017-01-23 15:08 UTC, jrietema commented on lib/supa/command.rb
> +      if exec_on_object?
See below... it's not a choice to exec on object but a choice not to exec on representer, a guard clause would also show that representer rendering is an exception:
```
return value_from_representer if exec_on_representer?
value_from_object
```

2017-01-23 15:08 UTC, jrietema commented on lib/supa/command.rb
> +      return context.send(getter) if context.respond_to?(getter)
needs more input validation: it's easy to fail `respond_to?` with an error if `getter` is not what expected

2017-01-23 15:08 UTC, jrietema commented on lib/supa/command.rb
> +      return context.send(getter) if context.respond_to?(getter)
I would like to raise an Exception rather than not returning anything if we don't have a Hash and the method is not defined on the object

2017-01-23 15:08 UTC, jrietema commented on spec/supa/commands/attribute_spec.rb
> +        pending('TBD')
Why is this pending? You could just call one of the methods on the `ArticleRepresenter`...

2017-01-23 15:08 UTC, jrietema commented on spec/supa/representable_spec.rb
> +            date: Date.today.iso8601.to_s
redundant `to_s` -> `Date.today.iso8601`

2017-01-23 15:08 UTC, jrietema commented on spec/supa/representable_spec.rb
> +            date: Date.today.iso8601.to_s
redundant `to_s` -> `Date.today.iso8601`

2017-01-23 15:08 UTC, jrietema commented on supa.gemspec
> +  spec.email         = ['info@distribusion.com', 'damir.mukimov@distribusion.com']
don't use `info@distribusion.com` :grin:

2017-01-23 15:10 UTC, goozzik commented on lib/supa/builder.rb
> +    def initialize(representer:, context:, tree:)
I think that context should be our main thing here so I would do this:

```ruby
def initialize(context, representer:, :tree)
```

2017-01-23 15:11 UTC, goozzik commented on lib/supa/command.rb
> +    def initialize(representer:, context:, tree:, name:, options: {}, &block)
https://github.com/distribusion/supa/pull/18/files#r97337211

2017-01-23 15:13 UTC, goozzik commented on lib/supa/command.rb
>      end
Please use `alias` or call `getter` directly when needed.

2017-01-23 15:20 UTC, goozzik commented on supa.gemspec
> -    jakub.gorzelak@distribusion.com
:(

2017-01-23 15:21 UTC, goozzik submitted a review, later dismissed
♻️

2017-01-23 17:50 UTC, Strech commented on supa.gemspec
> +    info@distribusion.com
please remove it

2017-01-23 17:51 UTC, Strech commented on spec/supa/representable_spec.rb
> +    subject { representer }
Please revert you changes on a `let` and make it back `subject`

2017-01-23 17:52 UTC, Strech commented on spec/supa/commands/attribute_spec.rb
> +  subject(:render_result) { attribute.represent }
Please read this doc https://github.com/distribusion/standards/wiki/RSpec#subject

2017-01-24 09:09 UTC, Strech requested changes
Need to adjust the code

2017-01-24 09:09 UTC, Strech commented on lib/supa/builder.rb
> +require 'supa/commands/append'
Let's move everything in one place, like `supa.rb`

2017-01-24 09:09 UTC, Strech commented on lib/supa/command.rb
> +      return context.send(getter) if context.respond_to?(getter)
what will happen if nothing is valid? `nil`? Is it a correct behavior?

2017-01-24 09:09 UTC, Strech commented on lib/supa/command.rb
> +      Array(value).any? || @options[:render_empty]
can we avoid array creation?

2017-01-24 09:09 UTC, Strech commented on lib/supa/command.rb
> +    def processed_value
this method is irresponsible

2017-01-24 09:09 UTC, Strech commented on lib/supa/commands/append.rb
> +require 'supa/command'
Please extract all require in one place

2017-01-24 09:09 UTC, Strech commented on lib/supa/commands/object.rb
> +        if context
guard?

2017-01-24 09:09 UTC, Strech commented on supa.gemspec
> -  spec.authors       = ['Andrey Duplichev', 'Jan Rietema', 'Jakub Gorzelak']
Please return proper names

2017-01-24 09:15 UTC, Strech commented
And the CodeClimate!

2017-01-25 15:59 UTC, Strech approved these changes
LGTM! 👍

2017-01-25 16:01 UTC, merged